package cn.com.venvy.common.utils;

import android.content.Context;
import android.content.SharedPreferences;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Build;
import android.provider.Settings;
import android.telephony.TelephonyManager;
import android.text.TextUtils;

import java.io.UnsupportedEncodingException;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.util.Enumeration;
import java.util.UUID;


/**
 * 计算宽高工具类
 *
 * @author John
 */
public class VenvyDeviceUtil {

    private static final String TAG = "VenvyDeviceUtil";
    private static final String PREFS_FILE = "device_id.xml";
    private static final String PREFS_DEVICE_ID = "device_id";
    protected static final String PREFS_ADINFO_ID = "adinfo_id";

	public static String getLanguage(Context context){
		return context.getResources()
				.getConfiguration().locale.getCountry();
	}
	public static String getUserAgent(){
		return android.os.Build.MODEL + "/"
				+ android.os.Build.VERSION.SDK + "/"
				+ android.os.Build.VERSION.RELEASE;
	}

	public static String getOsVersion() {
	    return Build.VERSION.RELEASE;
    }

    /**
     * 获取手机IMEI号，需要<uses-permission
     * android:name="android.permission.READ_PHONE_STATE" />
     *
     * @param context
     * @return
     */
    public static String getIMEI(Context context) {
        String IMEI = "";
        if (context == null) {
            return IMEI;
        }
        try {
            TelephonyManager telephonyManager = (TelephonyManager) context
                    .getSystemService(Context.TELEPHONY_SERVICE);
            IMEI = telephonyManager.getDeviceId();
            //md5加密
            IMEI = VenvyStringUtil.convertMD5(IMEI);
        } catch (Exception e) {
            IMEI = "";
        }
        return IMEI;
    }

    /**
     * 获取androidID
     *
     * @return
     */
    public static String getAndroidID(Context context) {
        String androidID = "";
        if (context == null) {
            return androidID;
        }
        try {
            androidID = Settings.System.getString(context.getContentResolver(),
                    Settings.System.ANDROID_ID);
            //md5加密
            androidID = VenvyStringUtil.convertMD5(androidID);
        } catch (Exception e) {
            androidID = "";
        }
        return androidID;
    }

    /***
     * 获取用户唯一标示
     * @param mContext
     * @return
     */
    public static String getClientId(Context mContext) {
        String clientId = VenvyPreferenceHelper.getString(mContext, "VideoJj-Live-clientID", null);
        if (!TextUtils.isEmpty(clientId))
            return clientId;
        else {
            clientId = String.valueOf(System.currentTimeMillis())
                    + VenvyRandomUtils.getRandomNumbersAndLetters(8);
            VenvyPreferenceHelper.putString(mContext, "VideoJj-Live-clientID", clientId);
            return clientId;
        }
    }

    /**
     * Returns a unique UUID for the current android device. As with all UUIDs, this unique ID is
     * "very highly likely" to be unique across all Android devices. Much more so than ANDROID_ID
     * is. The UUID is generated by using ANDROID_ID as the base key if appropriate, falling back on
     * TelephonyManager.getDeviceID() if ANDROID_ID is known to be incorrect, and finally falling
     * back on a random UUID that's persisted to SharedPreferences if getDeviceID() does not return
     * a usable value. In some rare circumstances, this ID may change. In particular, if the device
     * is factory reset a new device ID may be generated. In addition, if a user upgrades their
     * phone from certain buggy implementations of Android 2.2 to a newer, non-buggy version of
     * Android, the device ID may change. Or, if a user uninstalls your app on a device that has
     * neither a proper Android ID nor a Device ID, this ID may change on reinstallation. Note that
     * if the code falls back on using TelephonyManager.getDeviceId(), the resulting ID will NOT
     * change after a factory reset. Something to be aware of. Works around a bug in Android 2.2 for
     * many devices when using ANDROID_ID directly.
     *
     * @return a UUID that may be used to uniquely identify your device for most purposes.
     */
    public static UUID getDeviceUuid(Context context) {
        UUID uuid;
        synchronized (VenvyStringUtil.class) {
            final SharedPreferences prefs = context.getSharedPreferences(PREFS_FILE, 0);
            final String id = prefs.getString(PREFS_DEVICE_ID, null);
            if (id != null) {
                uuid = UUID.fromString(id);
            } else {
                final String androidId = Settings.Secure.getString(context.getContentResolver(),
                        Settings.Secure.ANDROID_ID);
                try {
                    if (!"9774d56d682e549c".equals(androidId)) {
                        uuid = UUID.nameUUIDFromBytes(androidId.getBytes("utf8"));
                    } else {
                        final String deviceId = ((TelephonyManager) context
                                .getSystemService(Context.TELEPHONY_SERVICE)).getDeviceId();
                        uuid = deviceId != null ? UUID.nameUUIDFromBytes(deviceId
                                .getBytes("utf8")) : UUID.randomUUID();
                    }
                } catch (UnsupportedEncodingException e) {
                    throw new RuntimeException(e);
                }
                prefs.edit().putString(PREFS_DEVICE_ID, uuid.toString()).commit();
            }
        }
        return uuid;
    }

    /**
     * 获取mac地址
     * need permissions required by WifiManager.getConnectionInfo: android.permission.ACCESS_WIFI_STATE
     */
    public static String getMacAddress(Context context) throws Exception {
//		// 在wifi未开启状态下，仍然可以获取MAC地址，但是IP地址必须在已连接状态下否则为0
//		String macAddress = "";
//		WifiManager wifiMgr = (WifiManager) context.getSystemService(Context.WIFI_SERVICE);
//		WifiInfo info = (null == wifiMgr ? null : wifiMgr.getConnectionInfo());
//		if (null != info) {
//			macAddress = info.getMacAddress();
//		}
//
//		return macAddress;
        return null;
    }

    /**
     * 获取IP地址
     */
    public static String getLocalIPAddress() {
        try {
            for (Enumeration<NetworkInterface> en = NetworkInterface.getNetworkInterfaces(); en
                    .hasMoreElements(); ) {
                NetworkInterface intf = en.nextElement();
                for (Enumeration<InetAddress> enumIpAddr = intf.getInetAddresses(); enumIpAddr
                        .hasMoreElements(); ) {
                    InetAddress inetAddress = enumIpAddr.nextElement();
                    if (!inetAddress.isLoopbackAddress() && (inetAddress instanceof Inet4Address)) {
                        return inetAddress.getHostAddress().toString();
                    }
                }
            }
        } catch (Exception ex) {
            VenvyLog.e(TAG, ex);
        }
        return null;
    }

    public static boolean isWifiConnected(Context context) {
        ConnectivityManager connectivityManager = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();
        if (networkInfo != null && networkInfo.isConnected()) {
            if (networkInfo.getType() == ConnectivityManager.TYPE_WIFI) {
                return true;
            }
        }
        return false;
    }

    public static String getNetWorkName(Context context) {
        String strNetworkType = "";
        ConnectivityManager connectivityManager = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();
        if (networkInfo != null && networkInfo.isConnected()) {
            if (networkInfo.getType() == ConnectivityManager.TYPE_WIFI) {
                strNetworkType = "WIFI";
            } else if (networkInfo.getType() == ConnectivityManager.TYPE_MOBILE) {
                String _strSubTypeName = networkInfo.getSubtypeName();
                VenvyLog.i("cocos2d-x", "Network getSubtypeName : " + _strSubTypeName);

                // TD-SCDMA   networkType is 17
                int networkType = networkInfo.getSubtype();
                switch (networkType) {
                    case TelephonyManager.NETWORK_TYPE_GPRS:
                    case TelephonyManager.NETWORK_TYPE_EDGE:
                    case TelephonyManager.NETWORK_TYPE_CDMA:
                    case TelephonyManager.NETWORK_TYPE_1xRTT:
                    case TelephonyManager.NETWORK_TYPE_IDEN: //api<8 : replace by 11
                        strNetworkType = "2G";
                        break;
                    case TelephonyManager.NETWORK_TYPE_UMTS:
                    case TelephonyManager.NETWORK_TYPE_EVDO_0:
                    case TelephonyManager.NETWORK_TYPE_EVDO_A:
                    case TelephonyManager.NETWORK_TYPE_HSDPA:
                    case TelephonyManager.NETWORK_TYPE_HSUPA:
                    case TelephonyManager.NETWORK_TYPE_HSPA:
                    case TelephonyManager.NETWORK_TYPE_EVDO_B: //api<9 : replace by 14
                    case TelephonyManager.NETWORK_TYPE_EHRPD:  //api<11 : replace by 12
                    case TelephonyManager.NETWORK_TYPE_HSPAP:  //api<13 : replace by 15
                        strNetworkType = "3G";
                        break;
                    case TelephonyManager.NETWORK_TYPE_LTE:    //api<11 : replace by 13
                        strNetworkType = "4G";
                        break;
                    default:
                        // http://baike.baidu.com/item/TD-SCDMA 中国移动 联通 电信 三种3G制式
                        if (_strSubTypeName.equalsIgnoreCase("TD-SCDMA") || _strSubTypeName.equalsIgnoreCase("WCDMA") || _strSubTypeName.equalsIgnoreCase("CDMA2000")) {
                            strNetworkType = "3G";
                        } else {
                            strNetworkType = _strSubTypeName;
                        }

                        break;
                }
                VenvyLog.i(TAG, "Network getSubtype : " + Integer.valueOf(networkType).toString());
            }
        }
        VenvyLog.i(TAG, "Network Type : " + strNetworkType);
        return strNetworkType;
    }
}
